name: snapd
version: 0.0.0-dev.3

description:
  Provides a client to access snapd, which is the local daemon that manages [snaps](https://snapcraft.io/).
  This is useful if you want to get information about installed snaps, or find and install more from the [snap store](https://snapcraft.io/store).

homepage: https://github.com/canonical/snapd.dart

environment:
  sdk: '>=2.7.2 <3.0.0'

dependencies:
  http: ^0.12.2

dev_dependencies:
  pedantic: ^1.9.0
